compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

initFields:
  version: 0.0.1
  license: BSD-3-Clause
  type: module

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  atls:
    npmRegistryServer: 'https://registry.npmjs.org'

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
